### ISSUE TITLE
Sync Failed: 404 while deleting

### ISSUE THREAD

**Issue by LukasLJL** [daullmer/rapla2caldav#1]
I created a new calendar and started syncing it with rapla, after the 2nd or 3rd run it fails with the following error:
```
Rapla and the calendar contain 68 same lectures
We need to add 12 lectures
We need to remove 9 lectures
Exception in thread "main" java.lang.Exception: [Internal CalDav]: Unexpected response code 404 while deleting
        at io.ullmer.caldav.CalDavClient.removeCalendarItem(CalDavClient.kt:53)
        at MainKt.main(Main.kt:52)
        at MainKt.main(Main.kt)
```

It looks like it wants to delete lectures but can not find them anymore, but in the Nextcloud calendar all synced lectures still exists.

**Comment by daullmer** [comment]
I ran into this issue as well. I think the happens when a lecture should be delete, but a calendar entry with the same id is already in the recycle bin. Clearing the recycle bin in Nextcloud should resolve this issue.

![Bildschirm­foto 2023-02-13 um 14 38 16](https://user-images.githubusercontent.com/16425113/218473685-fdc20155-61a3-47b3-a57d-a9a859c0d743.png)
![Bildschirm­foto 2023-02-13 um 14 38 51](https://user-images.githubusercontent.com/16425113/218473732-a516e95a-1592-4408-ab29-0b98a27f7915.png)

This is by no means a perfect solutions, since you usually don't notice it for some time

**Comment by LukasLJL** [comment]
Ok, thanks this helped :D
